---
title: "Australian beer production forecasting"
author: "Manish Kumar"
date: "8/14/2018"
output:
  pdf_document: default
  html_document: default
---

## Case Study

Analyze the historical beer production data and use time series forecasting techniques to forecast future beer production.

## load packages
```{r load packages,message=FALSE, warning=FALSE}
library(fpp2)  
library(astsa)  
library(DT)  
library(dygraphs)  
```

## load data
```{r load data, echo=T}
beer <- read.csv("data/monthly-beer-production-australia.csv")  
head(beer)
```
# basic analysis
```{r lower part of data, echo=T}
tail(beer)
```
```{r summarize data, echo=T}
summary(beer)
```
```{r convert to dataframe using ts, echo=T}
beer.ts <- ts(beer, frequency = 12, start = c(1956,1), end = c(1994,12))
```

```{r view ts converted dataframe, echo=T}
head(beer.ts)
```
# time series plots
```{r month level plots, echo=T}
plot.ts(beer.ts[,2], main = "Monthly Beer Production in Australia", xlab = "Year", ylab = "ML")
```

```{r quater level plot, echo=T}
# aggregared on quater level
beer.ts.qtr <- aggregate(beer.ts, nfrequency=4)
plot.ts(beer.ts.qtr[,2], main = "Quaterly Beer Production in Australia", xlab = "Year", ylab = "ML")
```

``` {r year level plot, echo=T}
# aggregared on year level
beer.ts.yr <- aggregate(beer.ts, nfrequency=1)
plot.ts(beer.ts.yr[,2], main = "Yearly Beer Production in Australia", xlab = "Year", ylab = "ML")
```
```{r seasonal plot, echo=T}
seasonplot(beer.ts[,2], year.labels = TRUE, year.labels.left=TRUE, col=1:40, pch=19, main = "Monthly Beer Production in Australia - seasonplot", xlab = "Month", ylab = "ML")
```

```{r monthly plot, echo=T}
# monthly plot aggreated the data of all year for montly analysis
# each month plots show the variation for entire data in each month
monthplot(beer.ts[,2], main = "Monthly Beer Production in Australia - monthplot", xlab = "Month", ylab = "ML")
```
```{r boxplot, echo=T}
boxplot(beer.ts[,2] ~ cycle(beer.ts[,2]), xlab = "Month", ylab = "ML", main = "Monthly Beer Production in Australia - Boxplot")
```
```{r moving average analysis, echo=T}
# moving average is useful when we need to analyse trend for the underlying data
# here, we see the moving average for 1 year, 3 year 5 year and 10 year
# Note : If there is not trend, average is good enough for the analysis
par(mfrow = c(2,2))
plot(beer.ts[,2], col="gray", main = "1 Year Moving Average Smoothing")
lines(ma(beer.ts[,2], order = 12), col = "red", lwd=3)
plot(beer.ts[,2], col="gray", main = "3 Year Moving Average Smoothing")
lines(ma(beer.ts[,2], order = 36), col = "blue", lwd=3)
plot(beer.ts[,2], col="gray", main = "5 Year Moving Average Smoothing")
lines(ma(beer.ts[,2], order = 60), col = "green", lwd=3)
plot(beer.ts[,2], col="gray", main = "10 Year Moving Average Smoothing")
lines(ma(beer.ts[,2], order = 120), col = "yellow4", lwd=3)
```


```{r data transformations and adjustments}
# adjusting and transformating data can makes the historical data less complex so a simpler
# forecast model can be used. It is also a good idea to remove the underline factors affected 
# the time series like workday, inflation, population, and currancy exchange rate etc.
```

```{r calendar adjustment}
# not all month have same days, so this variation should be removed for analysis, 
# also, so we will look at monthly sales dividing the number of working days in a month
# for better analysis
```

```{r monthly anayis raw, echo=T}
plot.ts(beer.ts[,2], main = "Monthly Beer Production in Australia", xlab = "Year", ylab = "ML")

```

```{r adjusted monthly analysis, echo=T}
plot.ts(beer.ts[,2]/monthdays(beer.ts[,2]), main = "Monthly Beer Production in Australia - Adjusted By Calendar Days", xlab = "Year", ylab = "ML")
```

## population adjustment
<!-- The beer production has been increased since last 50 years but
one thing to notice is that the population has also been increased in these year.
So, we need to analyse the data removing this factor.
Note: australian_population data is not available as of now, so we will not
do this adjustment but it needs to be taken care depeding on use-case.-->

## logarithmic transformation
<!-- Transform exponential trend line into a linear line using such transformations.
It is used before differencing data to improve stationarity.
-->

```{r before log transformatin, echo=T}
plot.ts(beer.ts[,2], main = "Monthly Beer Production in Australia", xlab = "Year", ylab = "ML")
```

```{r after log transformatin, echo=T}
plot.ts(log(beer.ts[,2]), main = "Log Transformated Monthly Beer Production in Australia", xlab = "Year", ylab = "ML")
```



